#!/bin/bash
F="public/index.html"
sed -i "s/^function svLS(/async function svLS(/" "$F"
sed -i "0,/firebase\.database()\.ref/{s|firebase\.database()\.ref|await firebase.database().ref|}" "$F"
sed -i "s/^function doLogin()/async function doLogin()/" "$F"
sed -i "/^async function doLogin/,/^}/{s|^  const acc=ACC\.find|  try{ACC=await ldFB('m2_acc',ACC)}catch(e){}\n  const acc=ACC.find|}" "$F"
sed -i "/localStorage\.setItem('m2_session'/a\  if(acc.r==='employee')localStorage.removeItem('m2_reg_submitted');" "$F"
sed -i "s/^function accPend(idx,ok){/async function accPend(idx,ok){/" "$F"
sed -i "s|PND\.splice(idx,1);svLS('m2_pnd',PND);svLS('m2_emps',EMPS);svLS('m2_acc',ACC);|PND.splice(idx,1);await Promise.all([svLS('m2_pnd',PND),svLS('m2_emps',EMPS),svLS('m2_acc',ACC)]);|" "$F"
sed -i "s/^function cfDel(){/async function cfDel(){/" "$F"
sed -i "/WARNS=WARNS\.filter(w=>w\.eid!==id);/a\  const delNm=document.getElementById('mDel').dataset.enm||'';NOTS=NOTS.filter(x=>!x.m||!x.m.includes(delNm));" "$F"
sed -i "s|svLS('m2_emps',EMPS);svLS('m2_att',ATT);svLS('m2_lvs',LVS);svLS('m2_deds',DEDS);svLS('m2_advs',ADVS);svLS('m2_acc',ACC);svLS('m2_warns',WARNS);|await Promise.all([svLS('m2_emps',EMPS),svLS('m2_att',ATT),svLS('m2_lvs',LVS),svLS('m2_deds',DEDS),svLS('m2_advs',ADVS),svLS('m2_acc',ACC),svLS('m2_warns',WARNS),svLS('m2_nots',NOTS)]);|" "$F"
sed -i "s/^function svWarn(){/async function svWarn(){/" "$F"
sed -i "s|svLS('m2_warns',WARNS);cM('mWarn');|await svLS('m2_warns',WARNS);cM('mWarn');|" "$F"
sed -i "s|svLS('m2_deds',DEDS);|await svLS('m2_deds',DEDS);|" "$F"
echo "All fixes applied!"
